### ISSUE TITLE
Invalid cookie lang

### ISSUE THREAD

**Issue by wdebusschere** [DeuxHuitHuit/flang_redirection#10]
With flang_redirection 2.0.0 my symphony log is full with 
03/11/2016 11:42 am > UNKNOWN: Exception 0 - Invalid cookie lang:  on line 150 of /Users/xxx/Sites/www.xxx.com/extensions/flang_redirection/events/event.flang_redirect.php
= when a visitor just enters the domain without language code in the url.

With flang_redirection 1.2.6 no errors in the log

Note: i don't experience this on the hosting, just local, on the hosting i get: 02/11/2016 6:43 pm > UNKNOWN: Exception 0 - Invalid language code. on line 331 of /home/xxx/www/extensions/frontend_localisation/lib/class.FLang.php

**Comment by nitriques** [comment]
I've removed the log entry. Thanks.
